#!/bin/bash
FILE=/run/stalwart-recovery.env
STALWART_USER=admin
STALWART_PASSWORD=$(head /dev/random  | sha256sum | awk '{print $1}')

echo "" > $FILE
if [ "$1" == "on" ]; then
	echo "STALWART_USER=$STALWART_USER" >> $FILE
	echo "STALWART_PASSWORD=$STALWART_PASSWORD" >> $FILE
	echo "STALWART_RECOVERY_MODE=1" >> $FILE
	echo "STALWART_RECOVERY_ADMIN=$STALWART_USER:$STALWART_PASSWORD" >> $FILE
	echo "STALWART_URL=http://127.0.0.1:8080/"
	echo "Recovery mode enabled"
	echo " Username: $STALWART_USER"
	echo " Password: $STALWART_PASSWORD"
	echo "Run the script again without a argument to disable the mode"
else
	echo "Recovery mode disabled, run this script with 'on' to enable it"
fi;
systemctl daemon-reload && systemctl restart stalwart
