#!/bin/bash
FILE=/run/stalwart-recovery.env
USERNAME=admin
PASSWORD=$(head /dev/random  | sha256sum | awk '{print $1}')

echo "" > $FILE
if [ "$1" == "on" ]; then
	echo "STALWART_RECOVERY_MODE=1" >> $FILE
	echo "STALWART_RECOVERY_ADMIN=$USERNAME:$PASSWORD" >> $FILE
	echo "Recovery mode enabled"
	echo " Username: $USERNAME"
	echo " Password: $PASSWORD"
	echo "Run the script again without a argument to disable the mode"
else
	echo "Recovery mode disabled, run this script with 'on' to enable it"
fi;
systemctl daemon-reload && systemctl restart stalwart
